name: Docker
on:
  workflow_dispatch:

jobs:
  playwright-run:
    runs-on: ubuntu-latest
    
    container:
      image: mcr.microsoft.com/playwright:focal
      options: --user root  
    
    env:
      HOME: /root 
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npm test

      - name: Upload Playwright Test Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: path/to/your/test/reports
