name: notify-failures

on:
  workflow_dispatch:

jobs:
  playwright-run:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:focal
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npm test || echo "Tests failed"

      - name: Upload Playwright Test Report
        if: always()  # Always upload report, even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Notify on test failures
        if: failure()  # Notify only if tests fail
        run: echo "Tests failed. Notify the team."
