name: PlaywrightTests
on: 
   workflow_dispatch: 

jobs:
  playwright-run:
    runs-on: ubuntu@latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
         node-version: 18

    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browser
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm playwright test
    - uses: actions/upload-artifacts@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
